import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import type { Sesion } from "@/lib/auth";
import type { Pedido } from "@/lib/taller-db";

type EstadoPush = "no-soportado" | "sin-clave" | "pendiente" | "activo" | "denegado" | "error";
type PasoPush = "validando" | "notification-api" | "permiso" | "service-worker" | "push-manager" | "vapid" | "vapid-conversion" | "supabase" | "edge-function" | "completo";
const PUSH_TIMEOUT_MS = 15_000;
const VAPID_PUBLIC_KEY_PILOTO = "BOPRpDYHJXszF0OBl1sQ9VfA7ORwghRP6U8tPVlUBozZVRDis6GhKM8rCy1EHpV8VUk6O0lxw5mj9qSJu8CPRcs";
type EdgeFunctionPayload = { pedido_id?: string; referencia?: string; cliente?: string; sede?: string; registrado_por?: string; prueba?: boolean; diagnostico?: boolean };
class PushDiagnosticoError extends Error { constructor(message: string, readonly categoria: string, readonly status?: number, readonly detalle?: unknown) { super(message); this.name = "PushDiagnosticoError"; } }
function vapidPublicKey() { return (import.meta.env["VITE_VAPID_PUBLIC_KEY"] as string | undefined) || VAPID_PUBLIC_KEY_PILOTO; }
function supabaseUrlPublica() { return import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"]; }
function supabasePublishableKey() { return import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"]; }
function urlBase64ToUint8Array(base64String: string) { const padding = "=".repeat((4 - (base64String.length % 4)) % 4); const rawData = window.atob(`${base64String}${padding}`.replace(/-/g, "+").replace(/_/g, "/")); const outputArray = new Uint8Array(rawData.length); for (let i = 0; i < rawData.length; i += 1) outputArray[i] = rawData.charCodeAt(i); return outputArray; }
function diagnosticoPush(paso: PasoPush, mensaje: string, extra?: unknown) { if (extra === undefined) console.info(`[push:${paso}] ${mensaje}`); else console.info(`[push:${paso}] ${mensaje}`, extra); }
function diagnosticoPushError(paso: PasoPush, mensaje: string, error?: unknown) { console.error(`[push:${paso}] ${mensaje}`, error); }
function diagnosticoPushOk(paso: PasoPush, mensaje: string, extra?: unknown) { if (extra === undefined) { console.info(`✓ ${mensaje}`); console.info(`[push:${paso}] OK`); } else { console.info(`✓ ${mensaje}`, extra); console.info(`[push:${paso}] OK`, extra); } }
function describirError(error: unknown) { if (error instanceof PushDiagnosticoError) return [error.message, error.status ? `HTTP ${error.status}` : ""].filter(Boolean).join(" - "); if (error instanceof Error) return error.message; if (typeof error === "string") return error; if (error && typeof error === "object" && "message" in error && typeof (error as {message?: unknown}).message === "string") return (error as {message: string}).message; return "Error desconocido"; }
function clasificarErrorEdge(status: number, payload?: unknown) { const texto = JSON.stringify(payload ?? {}).toLowerCase(); if (status === 0) return "Error de conexión"; if (status === 401) return "Error de autenticación"; if (status === 403) return "Error de permisos"; if (status === 404) return "Error Edge Function"; if (status >= 500 && texto.includes("vapid")) return "Error VAPID"; if (status >= 500 && texto.includes("environment")) return "Error de configuración"; return "Error Edge Function"; }
function normalizarRespuestaEdge(payload: unknown) { if (!payload || typeof payload !== "object") return "Respuesta vacía de la Edge Function"; const p = payload as {error?: unknown; detail?: unknown; details?: unknown; message?: unknown; missing?: unknown; empty?: unknown}; if (typeof p.message === "string") return p.message; const names = [...(Array.isArray(p.missing) ? p.missing : []), ...(Array.isArray(p.empty) ? p.empty : [])].filter((x): x is string => typeof x === "string"); if (names.length) return `Falta configurar: ${names.join(", ")}`; if (typeof p.error === "string") return p.error; if (typeof p.detail === "string") return p.detail; if (typeof p.details === "string") return p.details; return JSON.stringify(payload); }
function withTimeout<T>(promise: Promise<T>, mensaje: string, timeoutMs = PUSH_TIMEOUT_MS) { return new Promise<T>((resolve, reject) => { const timer = window.setTimeout(() => reject(new Error(mensaje)), timeoutMs); promise.then(v => { window.clearTimeout(timer); resolve(v); }).catch(e => { window.clearTimeout(timer); reject(e); }); }); }
async function ejecutarPaso<T>(paso: PasoPush, inicio: string, ok: string, tarea: () => Promise<T>, timeoutMs = PUSH_TIMEOUT_MS) { diagnosticoPush(paso, inicio); try { const r = await withTimeout(tarea(), `${inicio} excedió el tiempo de espera.`, timeoutMs); diagnosticoPushOk(paso, ok, resumenDiagnostico(r)); return r; } catch (e) { diagnosticoPushError(paso, `Falló: ${inicio}`, e); throw e; } }
function resumenDiagnostico(resultado: unknown) { if (!resultado || typeof resultado !== "object") return undefined; if ("scope" in resultado) return {scope: (resultado as ServiceWorkerRegistration).scope}; if ("endpoint" in resultado) { const s = resultado as PushSubscription; const j = s.toJSON(); return {endpoint: s.endpoint, hasP256dh: Boolean(j.keys?.["p256dh"]), hasAuth: Boolean(j.keys?.["auth"])}; } return undefined; }
async function invocarEdgeFunctionPush(payload: EdgeFunctionPayload) {
  const supabaseUrl = supabaseUrlPublica(); const publishableKey = supabasePublishableKey();
  if (!supabaseUrl || !publishableKey) throw new PushDiagnosticoError("Faltan variables públicas de Supabase en el frontend.", "Error de configuración");
  const {data: sessionData, error: sessionError} = await supabase.auth.getSession();
  if (sessionError) throw new PushDiagnosticoError(sessionError.message, "Error de autenticación", undefined, sessionError);
  const accessToken = sessionData.session?.access_token;
  if (!accessToken) throw new PushDiagnosticoError("No hay sesión activa para invocar la Edge Function.", "Error de autenticación");
  const url = `${supabaseUrl.replace(/\/$/, "")}/functions/v1/notify-new-order-owner`;
  diagnosticoPush("edge-function", "Invocando Edge Function", {url, diagnostico: Boolean(payload.diagnostico), prueba: Boolean(payload.prueba), hasAccessToken: Boolean(accessToken), pedido_id: payload.pedido_id});
  let response: Response;
  try { response = await withTimeout(fetch(url, {method: "POST", headers: {"content-type": "application/json", apikey: publishableKey, authorization: `Bearer ${accessToken}`}, body: JSON.stringify(payload)}), "La Edge Function no respondió a tiempo."); }
  catch (error) { throw new PushDiagnosticoError("No se pudo conectar con la Edge Function. Puede ser despliegue faltante, URL incorrecta o CORS.", "Error de conexión", 0, error); }
  const raw = await response.text(); let data: unknown = null; try { data = raw ? JSON.parse(raw) : null; } catch { data = raw; }
  diagnosticoPush("edge-function", "Respuesta Edge Function", {status: response.status, ok: response.ok, data});
  if (!response.ok) throw new PushDiagnosticoError(normalizarRespuestaEdge(data), clasificarErrorEdge(response.status, data), response.status, data);
  if (payload.diagnostico && data && typeof data === "object" && "ok" in data && (data as {ok?: unknown}).ok === false) throw new PushDiagnosticoError(normalizarRespuestaEdge(data), "Error VAPID", response.status, data);
  diagnosticoPushOk("edge-function", "Edge Function respondió correctamente.", data); return data;
}
async function obtenerRegistroServiceWorker() { const registration = await ejecutarPaso("service-worker", "Registrando Service Worker /sw.js", "Service Worker registrado.", () => navigator.serviceWorker.register("/sw.js", {scope: "/"})); diagnosticoPush("service-worker", "Estado del registro", {scope: registration.scope, active: Boolean(registration.active), installing: Boolean(registration.installing), waiting: Boolean(registration.waiting)}); return await ejecutarPaso("service-worker", "Esperando Service Worker listo", "Service Worker listo.", () => navigator.serviceWorker.ready); }
export function registrarServiceWorker() { if (typeof window === "undefined" || !("serviceWorker" in navigator)) return; const registrar = () => { navigator.serviceWorker.register("/sw.js", {scope: "/"}).then(r => diagnosticoPushOk("service-worker", "Service Worker registrado.", {scope: r.scope})).catch(e => diagnosticoPushError("service-worker", "No se pudo registrar el Service Worker", e)); }; if (document.readyState === "complete") { registrar(); return; } window.addEventListener("load", registrar, {once: true}); }
export function usePushDueno(sesion: Sesion | null | undefined) {
  const [estado, setEstado] = useState<EstadoPush>("pendiente"); const [cargando, setCargando] = useState(false); const [paso, setPaso] = useState<PasoPush | null>(null); const [mensaje, setMensaje] = useState<string | null>(null); const esDueno = Boolean(sesion?.esDueno); const clavePublica = useMemo(() => vapidPublicKey(), []);
  useEffect(() => { if (!esDueno || typeof window === "undefined") return; if (!window.isSecureContext || !("serviceWorker" in navigator) || !("PushManager" in window) || !("Notification" in window)) { setEstado("no-soportado"); return; } if (!clavePublica) { setEstado("sin-clave"); return; } if (Notification.permission === "denied") { setEstado("denegado"); return; } obtenerRegistroServiceWorker().then(r => r.pushManager.getSubscription()).then(async s => { setEstado(s ? "activo" : "pendiente"); if (!s || !sesion?.user.id) return; const j = s.toJSON(); const p256dh = j.keys?.["p256dh"] ?? ""; const auth = j.keys?.["auth"] ?? ""; if (!p256dh || !auth) return; await supabase.from("push_subscriptions").upsert({user_id: sesion.user.id, endpoint: s.endpoint, p256dh, auth, user_agent: navigator.userAgent}, {onConflict: "endpoint"}); }).catch(e => { diagnosticoPushError("service-worker", "No se pudo verificar suscripción existente", e); setEstado("pendiente"); }); }, [clavePublica, esDueno, sesion?.user.id]);
  async function activar() { if (!sesion?.esDueno || !clavePublica) return; if (!window.isSecureContext || !("serviceWorker" in navigator) || !("PushManager" in window) || !("Notification" in window)) { setEstado("no-soportado"); setMensaje("Este navegador no soporta notificaciones push web."); return; } let pasoActual: PasoPush = "validando"; const actualizarPaso = (siguiente: PasoPush, siguienteMensaje: string) => { pasoActual = siguiente; setPaso(siguiente); setMensaje(siguienteMensaje); }; setCargando(true); setEstado("pendiente"); actualizarPaso("validando", "Validando compatibilidad del navegador..."); try { actualizarPaso("notification-api", "Verificando Notification API..."); if (Notification.permission !== "granted") { const permiso = await Notification.requestPermission(); if (permiso !== "granted") { setEstado(permiso === "denied" ? "denegado" : "pendiente"); return; } } actualizarPaso("service-worker", "Preparando service worker..."); const registration = await obtenerRegistroServiceWorker(); actualizarPaso("vapid", "Leyendo clave pública VAPID..."); const applicationServerKey = urlBase64ToUint8Array(clavePublica); actualizarPaso("push-manager", "Creando suscripción push..."); const existente = await registration.pushManager.getSubscription(); const subscription = existente ?? await registration.pushManager.subscribe({userVisibleOnly: true, applicationServerKey}); const serializada = subscription.toJSON(); const p256dh = serializada.keys?.["p256dh"] ?? ""; const auth = serializada.keys?.["auth"] ?? ""; if (!subscription.endpoint || !p256dh || !auth) throw new Error("La suscripción push está incompleta."); actualizarPaso("supabase", "Guardando suscripción en Supabase..."); const resultadoGuardado = await ejecutarPaso("supabase", "Guardando suscripción en Supabase", "Suscripción guardada.", async () => await supabase.from("push_subscriptions").upsert({user_id: sesion.user.id, endpoint: subscription.endpoint, p256dh, auth, user_agent: navigator.userAgent}, {onConflict: "endpoint"})); if (resultadoGuardado.error) throw resultadoGuardado.error; actualizarPaso("edge-function", "Validando Edge Function de notificaciones..."); await ejecutarPaso("edge-function", "Validando Edge Function notify-new-order-owner", "Edge Function validada.", () => invocarEdgeFunctionPush({diagnostico: true})); actualizarPaso("completo", "Notificaciones activadas correctamente."); setEstado("activo"); toast.success("Notificaciones activadas para el Dueño"); } catch (error) { const mensajeError = describirError(error) || "No se pudieron activar notificaciones"; diagnosticoPushError(pasoActual, mensajeError, error); setEstado("error"); setMensaje(`${etiquetaErrorPaso[pasoActual] ?? "Activación"}: ${mensajeError}`); toast.error(mensajeError); } finally { setCargando(false); } }
  return {estado, cargando, paso, mensaje, activar};
}
const etiquetaErrorPaso: Partial<Record<PasoPush, string>> = {validando: "Validación del navegador", "notification-api": "Notification API", permiso: "Permiso del navegador", "service-worker": "Service Worker", "push-manager": "PushManager", vapid: "Clave VAPID", "vapid-conversion": "Conversión VAPID", supabase: "Guardado en Supabase", "edge-function": "Error Edge Function"};
export async function notificarNuevoPedidoADueno(pedido: Pick<Pedido, "id" | "referencia" | "cliente" | "sede_id">) {
  try {
    let sede = "";
    if (pedido.sede_id) { const {data} = await supabase.from("sedes").select("nombre").eq("id", pedido.sede_id).maybeSingle(); sede = data?.nombre ?? ""; }
    const {data: {user}} = await supabase.auth.getUser();
    let registrado_por = "";
    if (user?.id) { const {data} = await supabase.from("profiles").select("nombre").eq("id", user.id).maybeSingle(); registrado_por = data?.nombre ?? ""; }
    await invocarEdgeFunctionPush({pedido_id: pedido.id, referencia: pedido.referencia, cliente: pedido.cliente, sede, registrado_por});
  } catch (error) { console.warn("[push] No se pudo enviar notificación", {mensaje: describirError(error), error}); }
}
export async function enviarPruebaNotificacionDueno() { try { diagnosticoPush("edge-function", "Invocando prueba de notificación"); const data = await invocarEdgeFunctionPush({prueba: true, pedido_id: "prueba", referencia: "PRUEBA", cliente: "Notificación de prueba"}); toast.success("Notificación de prueba enviada al Dueño"); return data; } catch (error) { const mensaje = describirError(error) || "No se pudo enviar la notificación de prueba"; toast.error(mensaje); throw error; } }
