// @ts-nocheck -- tipos desalineados con el esquema real; pendiente regenerar tipos
import {useEffect,useState,type FormEvent} from "react";
import {Cake,Save,MessageCircle} from "lucide-react";
import {toast} from "sonner";
import {supabase} from "@/integrations/supabase/client";
import {useSesion} from "@/lib/auth";
const DEFAULT=["🎉 Feliz cumpleaños {nombre_cliente}","","Todo el equipo de {nombre_taller} te desea un excelente día.","","Gracias por confiar en nosotros."].join("\n");
const normalizarSaltos=(value:string)=>value.replace(/\\+n/g,"\n").replace(/\r\n?/g,"\n");
export function ConfiguracionMensajesCumpleanos({participanteId,sedeId}:{participanteId:string|null;sedeId:string|null}){
const {data:sesion}=useSesion(),[id,setId]=useState<string|null>(participanteId),[nombre,setNombre]=useState(sesion?.participante?.nombre??"Tu taller"),[mensaje,setMensaje]=useState(DEFAULT),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
useEffect(()=>{let live=true;void(async()=>{setLoading(true);try{let pid=participanteId;if(!pid&&sedeId){const r=await supabase.from("ecosistema_participantes").select("id,nombre").eq("sede_id",sedeId).eq("estado","activo").order("created_at").limit(1).maybeSingle();if(r.error)throw r.error;pid=r.data?.id??null;if(r.data?.nombre&&live)setNombre(r.data.nombre)}if(!pid)throw Error("Selecciona un taller concreto.");const r=await supabase.from("mensajes_automaticos_taller").select("mensaje_cumpleanos").eq("participante_id",pid).maybeSingle();if(r.error)throw r.error;if(live){setId(pid);setMensaje(r.data?.mensaje_cumpleanos||DEFAULT)}}catch(e){if(live)toast.error(e instanceof Error?e.message:"No se pudo cargar el mensaje")}finally{if(live)setLoading(false)}})();return()=>{live=false}},[participanteId,sedeId]);
async function save(e:FormEvent){e.preventDefault();if(!id||saving)return;if(!mensaje.includes("{nombre_cliente}")||!mensaje.includes("{nombre_taller}")){toast.error("Mantén las dos variables obligatorias.");return}setSaving(true);try{const r=await supabase.from("mensajes_automaticos_taller").upsert({participante_id:id,mensaje_cumpleanos:normalizarSaltos(mensaje),actualizado_por:sesion?.user?.id??null},{onConflict:"participante_id"});if(r.error)throw r.error;toast.success("Mensaje guardado para el taller")}catch{toast.error("No se pudo guardar. Revisa los permisos del taller")}finally{setSaving(false)}}
return <div className="grid gap-5 xl:grid-cols-2"><form onSubmit={save} className="rounded-2xl border border-border bg-card"><header className="flex items-center gap-3 border-b p-5"><Cake className="size-6 text-gold"/><div><h2 className="font-semibold">Mensajes Automáticos</h2><p className="text-xs text-muted-foreground">Configuración del taller</p></div></header><div className="space-y-4 p-5"><label className="block text-xs font-semibold">Mensaje de cumpleaños<textarea value={mensaje} onChange={e=>setMensaje(e.target.value)} rows={7} disabled={loading||!id} className="mt-2 w-full rounded-xl border border-border bg-background p-3 text-sm leading-6"/></label><p className="text-xs text-muted-foreground">Variables: <code>{"{nombre_cliente}"}</code> y <code>{"{nombre_taller}"}</code>.</p><button disabled={loading||saving||!id} className="rounded-xl bg-gold px-4 py-2.5 text-sm font-semibold text-gold-foreground"><Save className="mr-2 inline size-4"/>{saving?"Guardando…":"Guardar mensaje"}</button></div></form><aside className="rounded-2xl border border-border bg-card p-5"><h3 className="font-semibold"><MessageCircle className="mr-2 inline size-4 text-emerald-600"/>Vista previa</h3><p className="mt-3 whitespace-pre-wrap rounded-xl bg-surface-muted p-4 text-sm">{normalizarSaltos(mensaje).replaceAll("{nombre_cliente}","María").replaceAll("{nombre_taller}",nombre)}</p><p className="mt-3 text-xs text-muted-foreground">El saludo se prepara para revisión y envío manual por WhatsApp.</p></aside></div>
}