import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Panel } from "@/components/AppShell";
import { supabase } from "@/integrations/supabase/client";

type Estado = "pendiente" | "aprobada" | "pausada" | "rechazada";
type Solicitud = { id:string; tipo_solicitante:string; nombre:string; empresa:string|null; documento:string|null; email:string; telefono:string|null; ciudad:string|null; especialidades:string[]; descripcion:string|null; estado:Estado; notas_owner:string|null; revisado_por:string|null; revisado_at:string|null; created_at:string; };
const etiquetas: Record<string,string> = { taller:"Taller", profesional:"Profesional", proveedor:"Proveedor", servicio:"Servicio especializado" };

export function SolicitudesAccesoOwner() {
 const qc=useQueryClient();
 const [filtro,setFiltro]=useState<"todos"|Estado>("pendiente");
 const [seleccionada,setSeleccionada]=useState<Solicitud|null>(null);
 const [nota,setNota]=useState(""); const [guardando,setGuardando]=useState(false);
 const {data:solicitudes=[],isLoading,error}=useQuery({queryKey:["solicitudes-acceso",filtro],queryFn:async()=>{let q=supabase.from("solicitudes_acceso").select("*").order("created_at",{ascending:false});if(filtro!=="todos")q=q.eq("estado",filtro);const {data,error}=await q;if(error)throw error;return(data??[]) as Solicitud[];}});
 const resumen=useMemo(()=>({pendientes:solicitudes.filter(s=>s.estado==="pendiente").length,aprobadas:solicitudes.filter(s=>s.estado==="aprobada").length,pausadas:solicitudes.filter(s=>s.estado==="pausada").length,rechazadas:solicitudes.filter(s=>s.estado==="rechazada").length}),[solicitudes]);
 async function cambiarEstado(estado:Estado){if(!seleccionada)return;setGuardando(true);try{const user=(await supabase.auth.getUser()).data.user;const {error}=await supabase.from("solicitudes_acceso").update({estado,notas_owner:nota.trim()||null,revisado_por:estado==="pendiente"?null:user?.id??null,revisado_at:estado==="pendiente"?null:new Date().toISOString()}).eq("id",seleccionada.id);if(error)throw error;toast.success(estado==="aprobada"?"Solicitud aprobada":estado==="rechazada"?"Solicitud rechazada":estado==="pausada"?"Solicitud pausada":"Solicitud devuelta a pendientes");setSeleccionada(null);setNota("");await qc.invalidateQueries({queryKey:["solicitudes-acceso"]});}catch(e){toast.error(e instanceof Error?e.message:"No se pudo actualizar la solicitud");}finally{setGuardando(false);}}
 return <div className="space-y-6">
  <div className="grid gap-3 sm:grid-cols-4">{[
   ["pendiente","Pendientes",resumen.pendientes],["aprobada","Aprobadas",resumen.aprobadas],["pausada","Pausadas",resumen.pausadas],["rechazada","Rechazadas",resumen.rechazadas]
  ].map(([v,l,n])=><button key={String(v)} type="button" onClick={()=>setFiltro(v as Estado)} className={"rounded-xl border p-4 text-left "+(filtro===v?"border-primary bg-primary/5":"border-border bg-card")}><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{l}</p><p className="mt-1 text-2xl font-semibold">{n}</p></button>)}</div>
  <Panel titulo="Solicitudes de acceso al ecosistema">
   <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-4"><p className="text-xs text-muted-foreground">Revisión exclusiva del Dueño. Aprobar aquí no crea todavía una cuenta ni concede acceso automático.</p><button type="button" onClick={()=>setFiltro("todos")} className="rounded-lg border border-border px-3 py-2 text-xs">Ver todas</button></div>
   {error?<p className="p-6 text-sm text-destructive">No se pudieron cargar las solicitudes.</p>:null}{isLoading?<p className="p-6 text-sm text-muted-foreground">Cargando solicitudes…</p>:null}
   <div className="divide-y divide-border">{solicitudes.map(s=><button key={s.id} type="button" onClick={()=>{setSeleccionada(s);setNota(s.notas_owner??"");}} className="block w-full px-5 py-4 text-left hover:bg-surface-muted/50"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-semibold">{s.nombre}{s.empresa?" · "+s.empresa:""}</p><p className="text-xs text-muted-foreground">{etiquetas[s.tipo_solicitante]??s.tipo_solicitante} · {s.email}{s.ciudad?" · "+s.ciudad:""}</p></div><span className="rounded-full bg-surface-muted px-2.5 py-1 text-[10px] font-semibold uppercase">{s.estado}</span></div>{s.especialidades.length?<p className="mt-2 text-xs text-muted-foreground">{s.especialidades.join(" · ")}</p>:null}</button>)}{!isLoading&&solicitudes.length===0?<p className="p-8 text-sm text-muted-foreground">No hay solicitudes en este estado.</p>:null}</div>
  </Panel>
  {seleccionada?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setSeleccionada(null)}}><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-border bg-card shadow-xl">
   <div className="border-b border-border p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-lg font-semibold">{seleccionada.nombre}</p><p className="text-sm text-muted-foreground">{etiquetas[seleccionada.tipo_solicitante]??seleccionada.tipo_solicitante}{seleccionada.empresa?" · "+seleccionada.empresa:""}</p></div><button type="button" onClick={()=>setSeleccionada(null)} className="text-sm text-muted-foreground">Cerrar</button></div></div>
   <div className="grid gap-4 p-5 sm:grid-cols-2"><Dato label="Correo" value={seleccionada.email}/><Dato label="Teléfono" value={seleccionada.telefono}/><Dato label="Ciudad" value={seleccionada.ciudad}/><Dato label="Documento" value={seleccionada.documento}/><div className="sm:col-span-2"><Dato label="Especialidades" value={seleccionada.especialidades.join(", ")}/></div><div className="sm:col-span-2"><Dato label="Descripción" value={seleccionada.descripcion}/></div><label className="sm:col-span-2 text-xs text-muted-foreground">Nota interna del Dueño<textarea value={nota} onChange={e=>setNota(e.target.value)} rows={3} className="mt-1 w-full rounded-lg border border-border bg-background p-3 text-sm text-foreground outline-none focus:border-primary" placeholder="Observaciones, condiciones o próximos pasos…"/></label></div>
   <div className="flex flex-wrap gap-2 border-t border-border p-5"><button disabled={guardando} onClick={()=>void cambiarEstado("aprobada")} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50">Aprobar</button><button disabled={guardando} onClick={()=>void cambiarEstado("pausada")} className="rounded-lg border border-border px-4 py-2 text-sm disabled:opacity-50">Pausar</button><button disabled={guardando} onClick={()=>void cambiarEstado("rechazada")} className="rounded-lg border border-destructive/40 px-4 py-2 text-sm text-destructive disabled:opacity-50">Rechazar</button>{seleccionada.estado!=="pendiente"?<button disabled={guardando} onClick={()=>void cambiarEstado("pendiente")} className="rounded-lg border border-border px-4 py-2 text-sm disabled:opacity-50">Volver a pendiente</button>:null}</div>
  </div></div>:null}
 </div>;
}
function Dato({label,value}:{label:string;value:string|null|undefined}){return <div><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-sm">{value||"—"}</p></div>}
