import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Panel } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";

type Props={participanteId:string;participanteNombre:string;onClose:()=>void};
type Perfil={id:string;nombre:string;dni:string;telefono:string};
type Cuenta={id:string;user_id:string;relacion:"principal"|"miembro"|"contacto";estado:"activo"|"revocado"};

export function VincularCuentaParticipante({participanteId,participanteNombre,onClose}:Props){
 const qc=useQueryClient(); const [userId,setUserId]=useState("");
 const [relacion,setRelacion]=useState<Cuenta["relacion"]>("principal"); const [saving,setSaving]=useState(false);
 const {data:perfiles=[],isLoading}=useQuery({queryKey:["ecosistema-perfiles"],queryFn:async()=>{const {data,error}=await supabase.from("profiles").select("id,nombre,dni,telefono").order("nombre");if(error)throw error;return(data??[]) as Perfil[]}});
 const {data:cuentas=[]}=useQuery({queryKey:["participante-cuentas",participanteId],queryFn:async()=>{const {data,error}=await supabase.from("participante_cuentas").select("id,user_id,relacion,estado").eq("participante_id",participanteId);if(error)throw error;return(data??[]) as Cuenta[]}});
 const vinculados=new Set(cuentas.map(c=>c.user_id));
 const disponibles=perfiles.filter(p=>!vinculados.has(p.id));
 async function vincular(){if(!userId){toast.error("Selecciona una cuenta");return}setSaving(true);try{const {error}=await supabase.from("participante_cuentas").insert({participante_id:participanteId,user_id:userId,relacion,estado:"activo"});if(error)throw error;toast.success("Cuenta vinculada");setUserId("");await qc.invalidateQueries({queryKey:["participante-cuentas",participanteId]})}catch(e){toast.error(e instanceof Error?e.message:"No se pudo vincular")}finally{setSaving(false)}}
 async function cambiarEstado(c:Cuenta){const next=c.estado==="activo"?"revocado":"activo";const {error}=await supabase.from("participante_cuentas").update({estado:next}).eq("id",c.id);if(error)toast.error(error.message);else{toast.success(next==="activo"?"Cuenta reactivada":"Cuenta revocada");await qc.invalidateQueries({queryKey:["participante-cuentas",participanteId]})}}
 async function quitar(c:Cuenta){if(!confirm("¿Quitar esta vinculación?"))return;const {error}=await supabase.from("participante_cuentas").delete().eq("id",c.id);if(error)toast.error(error.message);else{toast.success("Vinculación eliminada");await qc.invalidateQueries({queryKey:["participante-cuentas",participanteId]})}}
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-border bg-card shadow-xl"><div className="border-b border-border p-5"><p className="text-lg font-semibold">Cuentas vinculadas</p><p className="text-xs text-muted-foreground">{participanteNombre} · solo el Dueño puede gestionar estas vinculaciones.</p></div><div className="space-y-5 p-5"><div className="rounded-xl border border-border p-4"><p className="mb-3 text-xs font-semibold uppercase tracking-wide">Vincular cuenta existente</p><div className="grid gap-3 sm:grid-cols-[1fr_180px_auto]"><select value={userId} onChange={e=>setUserId(e.target.value)} className="rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">{isLoading?"Cargando…":"Seleccionar usuario"}</option>{disponibles.map(p=><option key={p.id} value={p.id}>{p.nombre||p.dni} · {p.dni}</option>)}</select><select value={relacion} onChange={e=>setRelacion(e.target.value as Cuenta["relacion"])} className="rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="principal">Principal</option><option value="miembro">Miembro</option><option value="contacto">Contacto</option></select><Button disabled={saving||isLoading||!userId} onClick={()=>void vincular()}>Vincular</Button></div><p className="mt-2 text-[11px] text-muted-foreground">Esto no crea una cuenta nueva ni cambia el rol del usuario. Solo establece la relación con el participante.</p></div><Panel titulo={`Cuentas · ${cuentas.length}`}><div className="divide-y divide-border">{cuentas.map(c=>{const p=perfiles.find(x=>x.id===c.user_id);return <div key={c.id} className="flex items-center justify-between gap-3 px-5 py-3"><div><p className="text-sm font-medium">{p?.nombre||"Usuario"}</p><p className="text-xs text-muted-foreground">{p?.dni||c.user_id} · {c.relacion} · {c.estado}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>void cambiarEstado(c)}>{c.estado==="activo"?"Revocar":"Reactivar"}</Button><Button variant="ghost" size="sm" onClick={()=>void quitar(c)}>Quitar</Button></div></div>})}{!cuentas.length?<p className="p-6 text-sm text-muted-foreground">No hay cuentas vinculadas todavía.</p>:null}</div></Panel></div><div className="flex justify-end border-t border-border p-5"><Button variant="outline" onClick={onClose}>Cerrar</Button></div></div></div>
}