/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCorteLaserRouteImport } from './routes/_authenticated/corte-laser'
import { Route as AuthenticatedDiseno3dRouteImport } from './routes/_authenticated/diseno-3d'
import { Route as AuthenticatedGestionRouteImport } from './routes/_authenticated/gestion'
import { Route as AuthenticatedImpresion3dRouteImport } from './routes/_authenticated/impresion-3d'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedMonitorRouteImport } from './routes/_authenticated/monitor'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedTallerRouteImport } from './routes/_authenticated/taller'
import { Route as AuthenticatedPedidosIndexRouteImport } from './routes/_authenticated/pedidos.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCorteLaserRoute = AuthenticatedCorteLaserRouteImport.update({
  id: '/corte-laser',
  path: '/corte-laser',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiseno3dRoute = AuthenticatedDiseno3dRouteImport.update({
  id: '/diseno-3d',
  path: '/diseno-3d',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestionRoute = AuthenticatedGestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpresion3dRoute =
  AuthenticatedImpresion3dRouteImport.update({
    id: '/impresion-3d',
    path: '/impresion-3d',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonitorRoute = AuthenticatedMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTallerRoute = AuthenticatedTallerRouteImport.update({
  id: '/taller',
  path: '/taller',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosIndexRoute =
  AuthenticatedPedidosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPedidosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/corte-laser': typeof AuthenticatedCorteLaserRoute
  '/diseno-3d': typeof AuthenticatedDiseno3dRoute
  '/gestion': typeof AuthenticatedGestionRoute
  '/impresion-3d': typeof AuthenticatedImpresion3dRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/monitor': typeof AuthenticatedMonitorRoute
  '/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/taller': typeof AuthenticatedTallerRoute
  '/pedidos/': typeof AuthenticatedPedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/corte-laser': typeof AuthenticatedCorteLaserRoute
  '/diseno-3d': typeof AuthenticatedDiseno3dRoute
  '/gestion': typeof AuthenticatedGestionRoute
  '/impresion-3d': typeof AuthenticatedImpresion3dRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/monitor': typeof AuthenticatedMonitorRoute
  '/taller': typeof AuthenticatedTallerRoute
  '/pedidos': typeof AuthenticatedPedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/corte-laser': typeof AuthenticatedCorteLaserRoute
  '/_authenticated/diseno-3d': typeof AuthenticatedDiseno3dRoute
  '/_authenticated/gestion': typeof AuthenticatedGestionRoute
  '/_authenticated/impresion-3d': typeof AuthenticatedImpresion3dRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/monitor': typeof AuthenticatedMonitorRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/_authenticated/taller': typeof AuthenticatedTallerRoute
  '/_authenticated/pedidos/': typeof AuthenticatedPedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/corte-laser'
    | '/diseno-3d'
    | '/gestion'
    | '/impresion-3d'
    | '/inventario'
    | '/monitor'
    | '/pedidos'
    | '/taller'
    | '/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/corte-laser'
    | '/diseno-3d'
    | '/gestion'
    | '/impresion-3d'
    | '/inventario'
    | '/monitor'
    | '/taller'
    | '/pedidos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/corte-laser'
    | '/_authenticated/diseno-3d'
    | '/_authenticated/gestion'
    | '/_authenticated/impresion-3d'
    | '/_authenticated/inventario'
    | '/_authenticated/monitor'
    | '/_authenticated/pedidos'
    | '/_authenticated/taller'
    | '/_authenticated/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/corte-laser': {
      id: '/_authenticated/corte-laser'
      path: '/corte-laser'
      fullPath: '/corte-laser'
      preLoaderRoute: typeof AuthenticatedCorteLaserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diseno-3d': {
      id: '/_authenticated/diseno-3d'
      path: '/diseno-3d'
      fullPath: '/diseno-3d'
      preLoaderRoute: typeof AuthenticatedDiseno3dRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestion': {
      id: '/_authenticated/gestion'
      path: '/gestion'
      fullPath: '/gestion'
      preLoaderRoute: typeof AuthenticatedGestionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impresion-3d': {
      id: '/_authenticated/impresion-3d'
      path: '/impresion-3d'
      fullPath: '/impresion-3d'
      preLoaderRoute: typeof AuthenticatedImpresion3dRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitor': {
      id: '/_authenticated/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof AuthenticatedMonitorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taller': {
      id: '/_authenticated/taller'
      path: '/taller'
      fullPath: '/taller'
      preLoaderRoute: typeof AuthenticatedTallerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/': {
      id: '/_authenticated/pedidos/'
      path: '/'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AuthenticatedPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedPedidosRoute
    }
  }
}

interface AuthenticatedPedidosRouteChildren {
  AuthenticatedPedidosIndexRoute: typeof AuthenticatedPedidosIndexRoute
}

const AuthenticatedPedidosRouteChildren: AuthenticatedPedidosRouteChildren = {
  AuthenticatedPedidosIndexRoute: AuthenticatedPedidosIndexRoute,
}

const AuthenticatedPedidosRouteWithChildren =
  AuthenticatedPedidosRoute._addFileChildren(AuthenticatedPedidosRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCorteLaserRoute: typeof AuthenticatedCorteLaserRoute
  AuthenticatedDiseno3dRoute: typeof AuthenticatedDiseno3dRoute
  AuthenticatedGestionRoute: typeof AuthenticatedGestionRoute
  AuthenticatedImpresion3dRoute: typeof AuthenticatedImpresion3dRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedMonitorRoute: typeof AuthenticatedMonitorRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRouteWithChildren
  AuthenticatedTallerRoute: typeof AuthenticatedTallerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCorteLaserRoute: AuthenticatedCorteLaserRoute,
  AuthenticatedDiseno3dRoute: AuthenticatedDiseno3dRoute,
  AuthenticatedGestionRoute: AuthenticatedGestionRoute,
  AuthenticatedImpresion3dRoute: AuthenticatedImpresion3dRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedMonitorRoute: AuthenticatedMonitorRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRouteWithChildren,
  AuthenticatedTallerRoute: AuthenticatedTallerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
