create table if not exists public.piezas_terminadas (
 id uuid primary key default gen_random_uuid(), orden_produccion_id uuid not null references public.ordenes_produccion(id) on delete cascade, pedido_id uuid not null references public.pedidos(id) on delete cascade, numero_pieza text not null, cantidad integer not null default 1 check (cantidad > 0), peso_estimado numeric, peso_final numeric, unidad_peso text not null default 'g', metal_estimado text not null default '', metal_real text not null default '', piedras_estimadas text not null default '', piedras_reales text not null default '', estado text not null default 'pendiente', observaciones text not null default '', registrado_por uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint piezas_terminadas_estado_check check (estado in ('pendiente','recibida','verificada','liberada','rechazada')), constraint piezas_terminadas_peso_check check (peso_estimado is null or peso_estimado >= 0), constraint piezas_terminadas_peso_final_check check (peso_final is null or peso_final >= 0), unique (orden_produccion_id, numero_pieza));
create index if not exists piezas_terminadas_pedido_idx on public.piezas_terminadas(pedido_id, created_at desc);
create index if not exists piezas_terminadas_op_idx on public.piezas_terminadas(orden_produccion_id, created_at desc);
alter table public.piezas_terminadas enable row level security;
drop policy if exists "piezas leer sede" on public.piezas_terminadas;
create policy "piezas leer sede" on public.piezas_terminadas for select to authenticated using (exists (select 1 from public.ordenes_produccion op where op.id=orden_produccion_id and ve_sede(auth.uid(),op.sede_id)));
drop policy if exists "piezas crear sede" on public.piezas_terminadas;
create policy "piezas crear sede" on public.piezas_terminadas for insert to authenticated with check (registrado_por=auth.uid() and exists (select 1 from public.ordenes_produccion op where op.id=orden_produccion_id and ve_sede(auth.uid(),op.sede_id)));
drop policy if exists "piezas actualizar sede" on public.piezas_terminadas;
create policy "piezas actualizar sede" on public.piezas_terminadas for update to authenticated using (exists (select 1 from public.ordenes_produccion op where op.id=orden_produccion_id and ve_sede(auth.uid(),op.sede_id))) with check (exists (select 1 from public.ordenes_produccion op where op.id=orden_produccion_id and ve_sede(auth.uid(),op.sede_id)));
create or replace function public.touch_piezas_terminadas() returns trigger language plpgsql set search_path='' as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists trg_touch_piezas_terminadas on public.piezas_terminadas;
create trigger trg_touch_piezas_terminadas before update on public.piezas_terminadas for each row execute function public.touch_piezas_terminadas();
revoke execute on function public.touch_piezas_terminadas() from public,anon,authenticated;